### ISSUE TITLE
Error list index out of range with learner_html.check_HTML

### ISSUE THREAD

**Issue by JamesHF123** [MrMazzone/HTML-CSS-Grade#1]
Thank you for your efforts with this code it is very useful.
I do get an error with learner_html.check_HTML whenever I use it irrespective of the string I pass.

`learner_html.check_HTML("p")`
will produce the following error
`test_check_html (coding_rooms_unit_tests.CodingRoomsUnitTests) ... True
ERROR

======================================================================
ERROR: test_check_html (coding_rooms_unit_tests.CodingRoomsUnitTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usercode/coding_rooms_unit_tests.py", line 10, in test_check_html
    print(learner_html.check_HTML("p"))
  File "/usr/lib/python3/dist-packages/htmlcssgrade.py", line 50, in check_HTML
    return (code_snip.casefold().replace(" ", "").replace("\n", "") in str(self.html_obj.contents[2]).casefold().replace(" ", "").replace("\n", ""))
IndexError: list index out of range

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)`

my code is 

`import unittest
import htmlcssgrade

class CodingRoomsUnitTests(unittest.TestCase):

    def test_check_html(self):
        
        learner_html = htmlcssgrade.HTML_Check("index.html")
        print(learner_html.check_element_used("p"))
        print(learner_html.check_HTML("p"))`

any help would be much appreciated

**Comment by MrMazzone** [comment]
Hi @JamesHF123 . I am not seeing this error trying out some different things.  Can you send me the HTML file you are using to test?

**Comment by MrMazzone** [comment]
I just got that error if the HTML file is empty or does not exist.  Is that your case?

**Comment by JamesHF123** [comment]
I am testing the model answer

James Friendship
Head of Computing Science
[https://www.maynard.co.uk/wp-content/uploads/2022/01/dark-text-no-made-for-girls-RGB-small.png]
The Maynard School
Denmark Road, Exeter, Devon, EX1 1SJ
T:
+44 (0)1392 273417<tel:+44%20(0)1392%20273417>
W:
www.maynard.co.uk<https://www.maynard.co.uk>


Mrs L Gregory - Head
Mr H Luce - Chair of Governors

[https://www.maynard.co.uk/wp-content/uploads/2022/12/ISI-report-email-signature-01.12.22-v2.gif]<https://www.maynard.co.uk/>
This email and any attached files are confidential and intended solely for the use of the individual or entity to which they are addressed. The opinions expressed in this email and any attached files are the opinions of the author and do not necessarily represent the official views of The Maynard School. If you received this email in error please notify The Maynard School via ***@***.*** The Maynard School accepts no liability for any loss or damage that may be caused by computer viruses.
This email is transmitted in compliance with GDPR for details please visit our privacy policy.
The Maynard School is a company limited by guarantee.
Registered in England 4855372. Registered charity 1099027.

**Comment by JamesHF123** [comment]
No the index part appears to test ok. Is the model solution still saved as index.html? that could cause an issue.
I have however used the CSS part of the code to grab the whole code and that works ok.

James Friendship
Head of Computing Science
[https://www.maynard.co.uk/wp-content/uploads/2022/01/dark-text-no-made-for-girls-RGB-small.png]
The Maynard School
Denmark Road, Exeter, Devon, EX1 1SJ
T:
+44 (0)1392 273417<tel:+44%20(0)1392%20273417>
W:
www.maynard.co.uk<https://www.maynard.co.uk>


Mrs L Gregory - Head
Mr H Luce - Chair of Governors

[https://www.maynard.co.uk/wp-content/uploads/2022/12/ISI-report-email-signature-01.12.22-v2.gif]<https://www.maynard.co.uk/>
This email and any attached files are confidential and intended solely for the use of the individual or entity to which they are addressed. The opinions expressed in this email and any attached files are the opinions of the author and do not necessarily represent the official views of The Maynard School. If you received this email in error please notify The Maynard School via ***@***.*** The Maynard School accepts no liability for any loss or damage that may be caused by computer viruses.
This email is transmitted in compliance with GDPR for details please visit our privacy policy.
The Maynard School is a company limited by guarantee.
Registered in England 4855372. Registered charity 1099027.

**Comment by MrMazzone** [comment]
@JamesHF123 looks like if the HTML file has a different name or is empty it will throw that error.  I will update the library to give a friendlier error message in these cases.

**Comment by JamesHF123** [comment]
I am a bit confused if I run the test on the template which is called index.html I get the same error?

James Friendship
Head of Computing Science
[https://www.maynard.co.uk/wp-content/uploads/2022/01/dark-text-no-made-for-girls-RGB-small.png]
The Maynard School
Denmark Road, Exeter, Devon, EX1 1SJ
T:
+44 (0)1392 273417<tel:+44%20(0)1392%20273417>
W:
www.maynard.co.uk<https://www.maynard.co.uk>


Mrs L Gregory - Head
Mr H Luce - Chair of Governors

[https://www.maynard.co.uk/wp-content/uploads/2022/12/ISI-report-email-signature-01.12.22-v2.gif]<https://www.maynard.co.uk/>
This email and any attached files are confidential and intended solely for the use of the individual or entity to which they are addressed. The opinions expressed in this email and any attached files are the opinions of the author and do not necessarily represent the official views of The Maynard School. If you received this email in error please notify The Maynard School via ***@***.*** The Maynard School accepts no liability for any loss or damage that may be caused by computer viruses.
This email is transmitted in compliance with GDPR for details please visit our privacy policy.
The Maynard School is a company limited by guarantee.
Registered in England 4855372. Registered charity 1099027.

**Comment by MrMazzone** [comment]
Can you send me the html file?

**Comment by MrMazzone** [comment]
Closing this. Feel free to reopen if you have provide the test code and HTML file being graded.
